### ISSUE TITLE
Webui stop at login

### ISSUE THREAD

**Issue by ThaiThu** [openbmc/phosphor-webui#3] opened 2018-03-26 07:31 UTC
Hi all, the webui is already built to my BMC and when I browse to its address, it stops at "Login required", like this:

![image](https://user-images.githubusercontent.com/14868732/37892497-9b79e4f4-310a-11e8-8abb-ea5c8fce861b.png)
 So, how can I login to BMC Webui ?

Thanks !!

**Comment by gtmills** [comment] 2018-03-30 19:03
What system are you using? It looks to me like the WebUI package is not installed in the image. The only systems I know that has the WebUI installed in the image are Witherspoon and x86 systems.
https://github.com/openbmc/openbmc/blob/master/meta-openbmc-machines/meta-openpower/meta-ibm/meta-witherspoon/recipes-phosphor/packagegroups/packagegroup-obmc-apps.bbappend#L3

https://github.com/openbmc/openbmc/blob/master/meta-openbmc-machines/meta-x86/meta-intel/meta-common/recipes-intel/packagegroups/packagegroup-intel-apps.bb#L50

**Comment by gtmills** [comment] 2018-04-11 20:05
This is a duplicate of https://github.com/openbmc/openbmc/issues/3051. Closing this issue.

**Closed by gtmills** 2018-04-11 20:05 UTC
