### ISSUE TITLE
GUI: Server overview page re-appears for few seconds when navigating to User account page from Server overiew

### ISSUE THREAD

**Issue by adathatri** [openbmc/phosphor-webui#86] opened 2019-05-21 06:53 UTC
The existing page reloads before navigating to the user clicked page.
For eg:
Suppose we are on Server Overview page and Click on Users --> Manage user accounts. Server overview page reloads and appears for few seconds before User account page shows up.

**Comment by gtmills** [comment] 2019-05-23 01:14
@derick-montague @ryanarnell and I have noticed this as well.

**Comment by derick-montague** [comment] 2019-05-24 01:00
This is caused by the addition of the toast messages on 12/14/18. Removing the ngAnimate from the dependencies resolves the issue. I am working on resolving this issue.

Gerrit Review: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/16804

**Comment by derick-montague** [comment] 2019-05-24 03:41
Review ready: https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/21930

**Comment by derick-montague** [comment] 2019-05-28 17:53
@gtmills or @edtanous - Please assign this to me and move it to the current sprint lane. Although, given that we don't plan or work in Sprints for this repo, it might also make sense to change that lane title from "Current Sprint" to "In Progress". There is a review pending...See above.

**Closed** 2019-05-29 01:01 UTC
